# Generated by Django 5.0.6 on 2024-05-18 00:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('municipality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Calamity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('controlNumber', models.CharField(max_length=20)),
                ('givenBy', models.CharField(max_length=50)),
                ('donor', models.CharField(blank=True, max_length=50)),
                ('amount', models.IntegerField()),
                ('modeOfTransfer', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Distributed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repackedItem', models.IntegerField()),
                ('calamity', models.CharField(max_length=30)),
                ('calamityDate', models.DateField()),
                ('dateDistributed', models.DateField()),
                ('evacuee', models.CharField(max_length=50)),
                ('headFamily', models.CharField(max_length=20)),
                ('is_distributed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionBarangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12)),
                ('barangay', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('municipality', models.CharField(max_length=30)),
                ('barangay', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryPerBarangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12)),
                ('barangay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repacked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('units', models.TextField()),
                ('qty', models.TextField()),
                ('instance', models.IntegerField()),
                ('reason', models.TextField()),
                ('barangay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('municipality', models.CharField(max_length=50)),
                ('barangay', models.CharField(max_length=50)),
                ('contact_num', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('civil_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=50)),
                ('resident_status', models.CharField(max_length=20)),
                ('is_pwd', models.CharField(max_length=20)),
                ('is_ip', models.CharField(max_length=20)),
                ('is_head', models.CharField(max_length=20)),
                ('household_num', models.CharField(max_length=15)),
                ('street_add', models.CharField(max_length=250)),
                ('length_of_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('municipality', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentInEvacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHead', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('evacuation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.evacuation')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.resident')),
            ],
        ),
        migrations.CreateModel(
            name='StockedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenBy', models.CharField(max_length=50)),
                ('donor', models.CharField(blank=True, max_length=50)),
                ('dateReceived', models.DateField()),
                ('qty', models.DecimalField(decimal_places=1, max_digits=12)),
                ('expir_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
            ],
        ),
    ]
