# Generated by Django 5.0.6 on 2024-05-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_senior',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
